apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j3u1dqqy8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f96aebff43.ka8f.p3.openshiftapps.com/rhtap/rhtap-qe-go:e4e44a321ba156aafe5f1b97c3ebe20eced4f281@sha256:b8e58054e8f7c5923fdaecf43f08533c082c9d0e5c954d22598d5f38d6641db3
          name: container-image
